services:
  # bdd
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adventures
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API
  # api:
  #   build: 
  #     context: ./backend
  #     dockerfile: ../docker/Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/adventures

volumes:
  postgres_data:
